[window]
opacity = 0.8
startup_mode = "Fullscreen"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullScreen" },
]

[scrolling]
history = 65535

[terminal.shell]
program = "/usr/bin/tmux"
args = [ "new-session", "-A", "-s", "main" ]
